// Login Constants.
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// Signup Constants
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Credentials Constants.
export const CREDENTIALS_UPDATE = 'CREDENTIALS_UPDATE';

// Toggle between Login and Signup.
export const TOGGLE_LOGIN_VIEW = 'TOGGLE_LOGIN_VIEW';

// Field Validations.
export const VALIDATE_AUTH_FIELD = 'VALIDATE_AUTH_FIELD';
export const VALIDATE_USER_DETAILS_FIELD = 'VALIDATE_USER_DETAILS_FIELD';

// User Details Constants
export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';

export const USER_DETAILS_UPDATE_REQUEST = 'USER_DETAILS_UPDATE_REQUEST';
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_DETAILS_UPDATE_SUCCESS';
export const USER_DETAILS_UPDATE_FAILURE = 'USER_DETAILS_UPDATE_FAILURE';
export const TOGGLE_SHOW_USER_UPDATE_VIEW = 'TOGGLE_SHOW_USER_UPDATE_VIEW';
export const USER_DETAILS_FIELD_UPDATE = 'USER_DETAILS_FIELD_UPDATE';

// Utility Constants
export const CLEAR_SNACKBAR_MESSAGE = 'CLEAR_SNACKBAR_MESSAGE';
export const SHOW_SNACKBAR_MESSAGE = 'SHOW_SNACKBAR_MESSAGE';

// Documents Constants
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
