// Login Constants.
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// Signup Constants
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Credentials Constants.
export const CREDENTIALS_UPDATE = 'CREDENTIALS_UPDATE';

// Toggle between Login and Signup.
export const TOGGLE_LOGIN_VIEW = 'TOGGLE_LOGIN_VIEW';

// Field Validations.
export const VALIDATE_AUTH_FIELD = 'VALIDATE_AUTH_FIELD';
export const VALIDATE_USER_DETAILS_FIELD = 'VALIDATE_USER_DETAILS_FIELD';

// User Details Constants
export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';

export const USER_DETAILS_UPDATE_REQUEST = 'USER_DETAILS_UPDATE_REQUEST';
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_DETAILS_UPDATE_SUCCESS';
export const USER_DETAILS_UPDATE_FAILURE = 'USER_DETAILS_UPDATE_FAILURE';
export const TOGGLE_SHOW_USER_UPDATE_VIEW = 'TOGGLE_SHOW_USER_UPDATE_VIEW';
export const USER_DETAILS_FIELD_UPDATE = 'USER_DETAILS_FIELD_UPDATE';

// Utility Constants
export const CLEAR_SNACKBAR_MESSAGE = 'CLEAR_SNACKBAR_MESSAGE';
export const SHOW_SNACKBAR_MESSAGE = 'SHOW_SNACKBAR_MESSAGE';

// Documents Constants
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
export const EXPAND_DOCUMENT = 'EXPAND_DOCUMENT';

export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';

export const TOGGLE_CREATE_MODAL = 'TOGGLE_CREATE_MODAL';
export const UPDATE_NEW_DOCUMENT_CONTENTS = 'UPDATE_NEW_DOCUMENT_CONTENTS';
export const VALIDATE_NEW_DOCUMENT_CONTENTS = 'VALIDATE_NEW_DOCUMENT_CONTENTS';

export const DOCUMENT_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENT_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENT_UPDATE_FAILURE = 'DOCUMENT_UPDATE_FAILURE';
export const TOGGLE_SHOW_DOCUMENT_UPDATE = 'TOGGLE_SHOW_DOCUMENT_UPDATE';

export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';

export const CHANGE_DOCUMENTS_FILTER = 'CHANGE_DOCUMENTS_FILTER';
// Roles Constants.
export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
